on:
  workflow_dispatch:
jobs:
  demo_app_authentication:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Use the token
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh api octocat
      

      - uses: actions/checkout@v2
        with:
          token: ${{ GH_TOKEN }}

      - name: Config git credentials
        run: git config user.email "flubuild@microsoft.com" && git config user.name "Fluent Build System"

      - name: Commit version number change
        run: |
          date > generated.txt
          git add .
          git commit -m "Release 1.2.3"

      - name: Tag release
        run: git tag "1.2.3"

      - name: Push release
        run: |
          REMOTE_REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push $REMOTE_REPO
