name: Test Publish library

on:
  push:

env:
  LIBRARY_VERSION: 1.1.${{ github.run_number }}

jobs:
  publish-library:
    name: Publish icon libraries
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      actions: write

    steps:
    - uses: actions/checkout@v2
    
    - name: Config git credentials
      run: git config user.email "flubuild@microsoft.com" && git config user.name "Fluent Build System"

    - name: Commit version number change
      run: |
        git add -A
        git commit -m "Release $NEW_VERSION"
        
    - name: Tag release
      run: git tag "$NEW_VERSION"

    - name: Switch back to GH Actions
      run: |
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Push release
      run: |
        git push
